project:
  type: book
  output-dir: docs

book:
  title: "Old School D&D"
  author: "Ryan Hartman"
  date: "11/05/2025"
  reader-mode: true
  chapters:
    - index.qmd
    - part: Introduction
      chapters:
        - introduction/whatIsThis.qmd
        - introduction/basics.qmd
    - part: Player Characters
      chapters: 
        - characters/char-creation.qmd
        - characters/abilities.qmd
        - characters//races.qmd
        - characters/class.qmd
        - characters/backgrounds.qmd
        - characters/multiClass.qmd
        - characters/skills.qmd
        - characters/feats.qmd
        - characters/hitPoints.qmd
        - characters/languages.qmd
        - characters/equipment.qmd
        - characters/vehicles.qmd
    - part: Magic
      chapters: 
        - spells.qmd
        - allSpells.qmd
    - part: Adventure
      chapters: 
        - dungeonAdventures.qmd
        - wildAdventures.qmd
        - hirelings.qmd
        - advancement.qmd
    - part: Encounters
      chapters: 
        - combatOverview.qmd
        - combatDetails.qmd
        - savingThrows.qmd
        - healingAndInjuries.qmd
        - senses.qmd
    - part: Monsters
      chapters: 
        - monsters.qmd
        - monstersAll.qmd
        - monstersTab.qmd
    - part: Magical Items
      chapters: 
        - magicItems.qmd
        - namedMagicItems.qmd
    - part: DM Information
      chapters: 
        - gm01.qmd
        - gm02.qmd
        - treasure.qmd
        - randomMagicItems.qmd
    - part: The World of Greyhawk
      chapters:
        - 12Realms.qmd
        - history.qmd
        - gods.qmd
        - planes.qmd
    - part: Tables
      chapters: 
        - tables/npcs.qmd
        - tables/rivals.qmd     
    - part: Appendix
      chapters:
        - appendix_interactive.qmd
        - char_sheet.qmd
        - tables/frequent.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: Solar
    number-depth: 0
    css: [custom.css, styles.css]
    toc-depth: 4
    execute:
      echo: false
    header-includes: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Caudex">
    mainfont: "Caudex"
    include-after-body: toggle-images.html
  pdf:
    latex-template: "custom.tex"
    number-depth: 0
    toc-depth: 2
    toc: true
    execute:
      echo: false
    documentclass: report
    page-layout: full
    include-in-header: preamble.tex
  # pdf:
  #   documentclass: scrreprt